AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
  NewCops: disable

# Offense count: 48
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 176

# Offense count: 216
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 139

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Lint/ConstantResolution:
  Enabled: false