require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AwardsController, :type => :controller do

  let(:author) { create(:author) }
  let(:prize) { create(:prize) }
  let(:valid_attributes) { attributes_for(:award).merge(prize_id: prize.id) }
  # Note: Award doesn't validate year presence, so we can't test invalid params this way
  # If we want to test invalid params, we'd need to add a validation to the model
  let(:invalid_attributes) { { prize_id: nil } }
  let(:user) { create(:user, role: 'editor') }

  before do
    sign_in user
    # Stub load_awardable to return the author
    allow_any_instance_of(AwardsController).to receive(:load_awardable).and_return(author)
    controller.instance_variable_set(:@awardable, author)
  end

  describe "GET index" do
    it "assigns all awards as @awards" do
      award = create(:award)
      get :index
      expect(assigns(:awards)).to include(award)
    end
  end

  describe "GET edit" do
    it "assigns the requested award as @award" do
      award = create(:award, awardable: author)
      allow(controller.request).to receive(:path).and_return("/authors/#{author.id}/awards/#{award.id}/edit")
      get :edit, params: { author_id: author.id, id: award }
      expect(assigns(:award)).to eq(award)
    end
  end

  describe "POST create" do
    before do
      allow(controller.request).to receive(:path).and_return("/authors/#{author.id}/awards")
    end

    describe "with valid params" do
      it "creates a new Award" do
        expect {
          post :create, params: { author_id: author.id, award: valid_attributes }
        }.to change(Award, :count).by(1)
      end

      it "assigns a newly created award as @award" do
        post :create, params: { author_id: author.id, award: valid_attributes }
        expect(assigns(:award)).to be_a(Award)
        expect(assigns(:award)).to be_persisted
      end

      it "redirects to the awardable" do
        post :create, params: { author_id: author.id, award: valid_attributes }
        expect(response).to redirect_to(author)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved award as @award" do
        post :create, params: { author_id: author.id, award: invalid_attributes }
        expect(assigns(:award)).to be_a(Award)
        # Award model doesn't validate prize_id presence, so it might be persisted
        # If we want to test invalid params, we'd need to add a validation
        expect(assigns(:award)).to be_present
      end

      it "redirects to the awardable even with invalid params" do
        post :create, params: { author_id: author.id, award: invalid_attributes }
        expect(response).to redirect_to(author)
      end
    end
  end

  describe "PUT update" do
    let(:award) { create(:award, awardable: author) }

    before do
      allow(controller.request).to receive(:path).and_return("/authors/#{author.id}/awards/#{award.id}")
    end

    describe "with valid params" do
      let(:new_attributes) { { year: 2024 } }
      
      it "updates the requested award" do
        put :update, params: { author_id: author.id, id: award.id, award: new_attributes }
        award.reload
        expect(award.year).to eq(2024)
      end

      it "assigns the requested award as @award" do
        put :update, params: { author_id: author.id, id: award.id, award: valid_attributes }
        expect(assigns(:award)).to eq(award)
      end

      it "redirects to the awardable" do
        put :update, params: { author_id: author.id, id: award.id, award: valid_attributes }
        expect(response).to redirect_to(author)
      end
    end

    describe "with invalid params" do
      it "assigns the award as @award" do
        put :update, params: { author_id: author.id, id: award.id, award: invalid_attributes }
        expect(assigns(:award)).to eq(award)
      end

      it "redirects to the awardable even with invalid params" do
        put :update, params: { author_id: author.id, id: award.id, award: invalid_attributes }
        expect(response).to redirect_to(author)
      end
    end
  end

  describe "DELETE destroy" do
    let(:award) { create(:award, awardable: author) }

    before do
      allow(controller.request).to receive(:path).and_return("/authors/#{author.id}/awards/#{award.id}")
    end
    
    it "destroys the requested award" do
      award # Create the award
      expect {
        delete :destroy, params: { author_id: author.id, id: award.id }
      }.to change(Award, :count).by(-1)
    end

    it "redirects to the awardable" do
      delete :destroy, params: { author_id: author.id, id: award.id }
      expect(response).to redirect_to(author)
    end
  end

end
