require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContributionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Contribution. As you add validations to Contribution, be sure to
  # adjust the attributes here as well.
  let(:book) { create(:book) }
  let(:author) { create(:author) }
  let(:valid_attributes) { attributes_for(:contribution).merge(book_id: book.id, author_id: author.id) }
  let(:invalid_attributes) { { job: nil, book_id: book.id, author_id: author.id } }
  let(:user) { create(:user, role: 'editor') }

  before do
    sign_in user
  end

  describe "GET index" do
    it "assigns all contributions as @contributions" do
      contribution = create(:contribution)
      get :index
      expect(assigns(:contributions)).to eq([contribution])
    end
  end

  describe "GET show" do
    it "assigns the requested contribution as @contribution" do
      contribution = create(:contribution)
      get :show, params: { id: contribution }
      expect(assigns(:contribution)).to eq(contribution)
    end
  end

  describe "GET new" do
    it "assigns a new contribution as @contribution" do
      get :new
      expect(assigns(:contribution)).to be_a_new(Contribution)
    end
  end

  describe "GET edit" do
    it "assigns the requested contribution as @contribution" do
      contribution = create(:contribution)
      get :edit, params: { id: contribution }
      expect(assigns(:contribution)).to eq(contribution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contribution" do
        expect {
          post :create, params: { contribution: valid_attributes }
        }.to change(Contribution, :count).by(1)
      end

      it "assigns a newly created contribution as @contribution" do
        post :create, params: { contribution: valid_attributes }
        expect(assigns(:contribution)).to be_a(Contribution)
        expect(assigns(:contribution)).to be_persisted
      end

      it "redirects to the created contribution" do
        post :create, params: { contribution: valid_attributes }
        expect(response).to redirect_to(Contribution.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contribution as @contribution" do
        post :create, params: { contribution: invalid_attributes }
        expect(assigns(:contribution)).to be_a(Contribution)
        expect(assigns(:contribution)).not_to be_persisted
      end

      it "re-renders the 'new' template" do
        post :create, params: { contribution: invalid_attributes }
        # The controller uses respond_with which re-renders on validation errors
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) { { job: :μετάφραση } } # Second enum value

      it "updates the requested contribution" do
        contribution = create(:contribution)
        put :update, params: { id: contribution, contribution: new_attributes }
        contribution.reload
        expect(contribution.job).to eq("μετάφραση")
      end

      it "assigns the requested contribution as @contribution" do
        contribution = create(:contribution)
          put :update, params: { id: contribution, contribution: valid_attributes }
        expect(assigns(:contribution)).to eq(contribution)
      end

      it "redirects to the contribution" do
        contribution = create(:contribution)
          put :update, params: { id: contribution, contribution: valid_attributes }
        expect(response).to redirect_to(contribution)
      end
    end

    describe "with invalid params" do
      it "assigns the contribution as @contribution" do
        contribution = create(:contribution)
        put :update, params: { id: contribution, contribution: invalid_attributes }
        expect(assigns(:contribution)).to eq(contribution)
      end

      it "re-renders the 'edit' template" do
        contribution = create(:contribution)
        put :update, params: { id: contribution, contribution: invalid_attributes }
        # The controller uses respond_with which re-renders on validation errors
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contribution" do
      contribution = create(:contribution)
      expect {
          delete :destroy, params: { id: contribution }
      }.to change(Contribution, :count).by(-1)
    end

    it "redirects to the contributions list" do
      contribution = create(:contribution)
          delete :destroy, params: { id: contribution }
      expect(response).to redirect_to(contributions_url)
    end
  end

end
