require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlacesController, :type => :controller do

  let(:valid_attributes) { attributes_for(:place) }
  let(:invalid_attributes) { { address: nil } }
  let(:user) { create(:user, role: 'editor') }
  let(:publisher) { create(:publisher) }
  let(:place) { create(:place, placeable: publisher) }

  before do
    sign_in user
    # Stub load_placeable to return the publisher
    allow_any_instance_of(PlacesController).to receive(:load_placeable).and_return(publisher)
    controller.instance_variable_set(:@placeable, publisher)
  end

  describe "GET edit" do
    it "assigns the requested place as @place" do
      allow(controller.request).to receive(:path).and_return("/publishers/#{publisher.id}/places/#{place.id}/edit")
      get :edit, params: { publisher_id: publisher.id, id: place }
      expect(assigns(:place)).to eq(place)
    end
  end

  describe "POST create" do
    before do
      # Set up the request path so load_placeable can parse it
      allow(controller.request).to receive(:path).and_return("/publishers/#{publisher.id}/places")
    end

    describe "with valid params" do
      it "creates a new Place" do
        expect {
          post :create, params: { publisher_id: publisher.id, place: valid_attributes }
        }.to change(Place, :count).by(1)
      end

      it "assigns a newly created place as @place" do
        post :create, params: { publisher_id: publisher.id, place: valid_attributes }
        expect(assigns(:place)).to be_a(Place)
        expect(assigns(:place)).to be_persisted
      end

      it "redirects to the placeable" do
        post :create, params: { publisher_id: publisher.id, place: valid_attributes }
        expect(response).to redirect_to(publisher)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved place as @place" do
        post :create, params: { publisher_id: publisher.id, place: invalid_attributes }
        expect(assigns(:place)).to be_a(Place)
        expect(assigns(:place)).not_to be_persisted
      end

      it "redirects to the placeable even with invalid params" do
        post :create, params: { publisher_id: publisher.id, place: invalid_attributes }
        expect(response).to redirect_to(publisher)
      end
    end
  end

  describe "PUT update" do
    before do
      allow(controller.request).to receive(:path).and_return("/publishers/#{publisher.id}/places/#{place.id}")
    end

    describe "with valid params" do
      let(:new_attributes) { { name: "New Place Name" } }

      it "updates the requested place" do
        put :update, params: { publisher_id: publisher.id, id: place, place: new_attributes }
        place.reload
        expect(place.name).to eq("New Place Name")
      end

      it "assigns the requested place as @place" do
        put :update, params: { publisher_id: publisher.id, id: place, place: valid_attributes }
        expect(assigns(:place)).to eq(place)
      end

      it "redirects to the placeable" do
        put :update, params: { publisher_id: publisher.id, id: place, place: valid_attributes }
        expect(response).to redirect_to(publisher)
      end
    end

    describe "with invalid params" do
      it "assigns the place as @place" do
        put :update, params: { publisher_id: publisher.id, id: place, place: invalid_attributes }
        expect(assigns(:place)).to eq(place)
      end

      it "redirects to the placeable even with invalid params" do
        put :update, params: { publisher_id: publisher.id, id: place, place: invalid_attributes }
        expect(response).to redirect_to(publisher)
      end
    end
  end

  describe "DELETE destroy" do
    before do
      allow(controller.request).to receive(:path).and_return("/publishers/#{publisher.id}/places/#{place.id}")
    end

    it "destroys the requested place" do
      place # Create the place
      expect {
        delete :destroy, params: { publisher_id: publisher.id, id: place }
      }.to change(Place, :count).by(-1)
    end

    it "redirects to the placeable" do
      delete :destroy, params: { publisher_id: publisher.id, id: place }
      expect(response).to redirect_to(publisher)
    end
  end


end
