require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProfilesController, :type => :controller do

  let(:valid_attributes) { { name: "New Profile Name" } }
  let(:invalid_attributes) { { username: nil } }
  let(:user) { create(:user, role: 'editor') }
  let(:profile) { user.profile }

  before do
    sign_in user
  end

  describe "GET show" do
    it "assigns the requested profile as @profile" do
      get :show, params: { id: profile.id }
      expect(assigns(:profile)).to eq(profile)
    end
  end

  describe "GET edit" do
    it "assigns the current user's profile as @profile" do
      get :edit
      expect(assigns(:profile)).to eq(profile)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested profile" do
        put :update, params: { profile: valid_attributes }
        profile.reload
        expect(profile.name).to eq("New Profile Name")
      end

      it "assigns the requested profile as @profile" do
        put :update, params: { profile: valid_attributes }
        expect(assigns(:profile)).to eq(profile)
      end

      it "redirects to the profile" do
        put :update, params: { profile: valid_attributes }
        expect(response).to redirect_to(public_profile_path(profile.id))
      end
    end

    describe "with invalid params" do
      it "assigns the profile as @profile" do
        put :update, params: { profile: invalid_attributes }
        expect(assigns(:profile)).to eq(profile)
      end

      it "redirects to the profile even with invalid params" do
        put :update, params: { profile: invalid_attributes }
        expect(response).to redirect_to(public_profile_path(profile.id))
      end
    end
  end

end
