require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PublishersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Publisher. As you add validations to Publisher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for(:publisher) }
  let(:invalid_attributes) { { name: nil } }
  let(:valid_session) { {} }
  let(:user) { create(:user, :editor) }

  before do
    sign_in user
  end

  describe "GET index" do
    it "assigns all publishers as @publishers" do
      publisher = create(:publisher)
      get :index
      expect(assigns(:publishers)).to eq([publisher])
    end
  end

  describe "GET show" do
    it "assigns the requested publisher as @publisher" do
      publisher = create(:publisher)
      get :show, params: { id: publisher }
      expect(assigns(:publisher)).to eq(publisher)
    end
  end

  describe "GET new" do
    it "assigns a new publisher as @publisher" do
      get :new
      expect(assigns(:publisher)).to be_a_new(Publisher)
    end
  end

  describe "GET edit" do
    it "assigns the requested publisher as @publisher" do
      publisher = create(:publisher)
      get :edit, params: { id: publisher }
      expect(assigns(:publisher)).to eq(publisher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Publisher" do
        expect {
          post :create, params: { publisher: valid_attributes }
        }.to change(Publisher, :count).by(1)
      end

      it "assigns a newly created publisher as @publisher" do
        post :create, params: { publisher: valid_attributes }
        expect(assigns(:publisher)).to be_a(Publisher)
        expect(assigns(:publisher)).to be_persisted
      end

      it "redirects to the created publisher" do
        post :create, params: { publisher: valid_attributes }
        expect(response).to redirect_to(Publisher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publisher as @publisher" do
        post :create, params: { publisher: invalid_attributes }
        expect(assigns(:publisher)).to be_a_new(Publisher)
      end

      it "re-renders the 'new' template" do
        post :create, params: { publisher: invalid_attributes }
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) { { name: "New Publisher Name" } }

      it "updates the requested publisher" do
        publisher = create(:publisher)
        put :update, params: { id: publisher, publisher: new_attributes }
        publisher.reload
        expect(publisher.name).to eq("New Publisher Name")
      end

      it "assigns the requested publisher as @publisher" do
        publisher = create(:publisher)
        put :update, params: { id: publisher, publisher: valid_attributes }
        expect(assigns(:publisher)).to eq(publisher)
      end

      it "redirects to the publisher" do
        publisher = create(:publisher)
        put :update, params: { id: publisher, publisher: valid_attributes }
        expect(response).to redirect_to(publisher)
      end
    end

    describe "with invalid params" do
      it "assigns the publisher as @publisher" do
        publisher = create(:publisher)
        put :update, params: { id: publisher, publisher: invalid_attributes }
        expect(assigns(:publisher)).to eq(publisher)
      end

      it "re-renders the 'edit' template" do
        publisher = create(:publisher)
        put :update, params: { id: publisher, publisher: invalid_attributes }
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publisher" do
      publisher = create(:publisher)
      expect {
          delete :destroy, params: { id: publisher }
      }.to change(Publisher, :count).by(-1)
    end

    it "redirects to the publishers list" do
      publisher = create(:publisher)
          delete :destroy, params: { id: publisher }
      expect(response).to redirect_to(publishers_url)
    end
  end

end
